rules:
  empty-line-between-blocks:
    - 0
  indentation:
    - 1
    - size: 2
  nesting-depth:
    - 1
    - max-depth: 10
  property-sort-order:
    - 0
  no-duplicate-properties:
    - 0
  no-vendor-prefixes:
    - 0
  quotes:
    - 1
    - style: double
  no-important:
    - 1
